// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hdozkvjywctfknazfivy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhkb3prdmp5d2N0ZmtuYXpmaXZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4OTAxNTEsImV4cCI6MjA2NDQ2NjE1MX0.OmkwuctFvUfIY2-LLhaZGEti2v5LHDlAl0PNCVxzq2U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);